/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_intermodalics_tangoxros_TangoRosNode */

#ifndef _Included_eu_intermodalics_tangoxros_TangoRosNode
#define _Included_eu_intermodalics_tangoxros_TangoRosNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_intermodalics_tangoxros_TangoRosNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_intermodalics_tangoxros_TangoRosNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     eu_intermodalics_tangoxros_TangoRosNode
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_intermodalics_tangoxros_TangoRosNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
